// <auto-generated />
using System;
using IdentityHub.IdentityService.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityHub.IdentityService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20260131114236_Refactoring_Security")]
    partial class Refactoring_Security
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.AuthMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AuthData")
                        .HasColumnType("text")
                        .HasColumnName("AuthData");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AuthKey");

                    b.Property<int>("AuthType")
                        .HasColumnType("integer")
                        .HasColumnName("AuthType");

                    b.Property<string>("Salt")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Salt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuthMethod", (string)null);
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.SecureData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("SecureDataType")
                        .HasColumnType("integer")
                        .HasColumnName("SecureDataType");

                    b.Property<string>("SecureEncryptedMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("SecureEncryptedMetadata");

                    b.Property<string>("SecureEncryptedValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SecureEncryptedValue");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SecureData", (string)null);
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.ToTable("Statuses", (string)null);
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("DateEntry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateEntry");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateRegistration");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateUpdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email")
                        .UseCollation("case_insensitive");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Login")
                        .UseCollation("case_insensitive");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("text")
                        .HasColumnName("Phone")
                        .UseCollation("case_insensitive");

                    b.Property<Guid[]>("RoleIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("RoleIds");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.AuthMethod", b =>
                {
                    b.HasOne("IdentityHub.IdentityService.Domain.Models.User", null)
                        .WithMany("AuthMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.SecureData", b =>
                {
                    b.HasOne("IdentityHub.IdentityService.Domain.Models.User", null)
                        .WithMany("SecureDatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.User", b =>
                {
                    b.HasOne("IdentityHub.IdentityService.Domain.Models.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityHub.IdentityService.Domain.Models.User", b =>
                {
                    b.Navigation("AuthMethods");

                    b.Navigation("SecureDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
